# -*- coding: utf-8 -*-
"""COVID_19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9lBRqvo6BfSsbLQNVpL9PB6B-n3o1YN

**OBJECTIVE 1 – DATA COLLECTION**

**1 – Install Libraries**
"""

!pip install dash==2.14.2 jupyter-dash==0.4.2

!pip install dash jupyter-dash plotly seaborn

"""**2 – Import Libraries**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px

from jupyter_dash import JupyterDash
from dash import dcc, html
from dash.dependencies import Input, Output

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/country_wise_latest.csv")
df = df[["Country/Region", "Confirmed", "Deaths", "Recovered", "Active"]]
df.columns = ["Country", "Confirmed", "Deaths", "Recovered", "Active"]
df = df.drop_duplicates()
df[["Confirmed","Deaths","Recovered","Active"]] = df[
    ["Confirmed","Deaths","Recovered","Active"]
].apply(pd.to_numeric, errors='coerce')

top10 = df.sort_values(by="Confirmed", ascending=False).head(10)

total_confirmed = df["Confirmed"].sum()
total_deaths = df["Deaths"].sum()
total_recovered = df["Recovered"].sum()
total_active = df["Active"].sum()

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/country_wise_latest.csv")

df = df[["Country/Region", "Confirmed", "Deaths", "Recovered", "Active"]]
df.columns = ["Country", "Confirmed", "Deaths", "Recovered", "Active"]

df = df.drop_duplicates()

df[["Confirmed","Deaths","Recovered","Active"]] = df[
    ["Confirmed","Deaths","Recovered","Active"]
].apply(pd.to_numeric, errors='coerce')

top10 = df.sort_values(by="Confirmed", ascending=False).head(10)

total_confirmed = df["Confirmed"].sum()
total_deaths = df["Deaths"].sum()
total_recovered = df["Recovered"].sum()
total_active = df["Active"].sum()

"""**3 – Load Dataset**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/country_wise_latest.csv")

df.head()

"""**OBJECTIVE 2 – DATA CLEANING & PREPROCESSING**

**4 – Select Required Columns**
"""

df = df[["Country/Region", "Confirmed", "Deaths", "Recovered", "Active"]]

df.columns = ["Country", "Confirmed", "Deaths", "Recovered", "Active"]

df.head()

"""**5 – Check Missing Values**"""

print("Missing Values:\n")
print(df.isnull().sum())

"""**6 – Remove Duplicates**"""

df = df.drop_duplicates()

df.info()

"""**7 – Convert Data Types**"""

df[["Confirmed","Deaths","Recovered","Active"]] = df[
    ["Confirmed","Deaths","Recovered","Active"]
].apply(pd.to_numeric, errors='coerce')

"""**OBJECTIVE 3 – DESCRIPTIVE STATISTICS**

**8 – Global Statistics**
"""

total_confirmed = df["Confirmed"].sum()
total_deaths = df["Deaths"].sum()
total_recovered = df["Recovered"].sum()
total_active = df["Active"].sum()

print("Total Confirmed:", total_confirmed)
print("Total Deaths:", total_deaths)
print("Total Recovered:", total_recovered)
print("Total Active:", total_active)

"""**9 – Statistical Summary**"""

df.describe()

"""**OBJECTIVE 4 – COUNTRY-BASED ANALYSIS**

**10 – Top 10 Countries**
"""

top10 = df.sort_values(by="Confirmed", ascending=False).head(10)

top10

# Create clean pie data (RUN THIS CELL ONCE)

top5 = df.sort_values(by="Confirmed", ascending=False).head(5)

others = pd.DataFrame({
    "Country": ["Others"],
    "Confirmed": [df["Confirmed"].sum() - top5["Confirmed"].sum()]
})

pie_data = pd.concat([top5[["Country","Confirmed"]], others])

"""**11 – Bar Chart (Confirmed Cases)**"""

fig = px.bar(
    top10,
    x="Confirmed",
    y="Country",
    title="Top 10 Countries - Confirmed Cases"
)

fig.show()

"""**12 – Bar Chart (Deaths)**"""

fig = px.bar(
    top10,
    x="Deaths",
    y="Country",
    title="Top 10 Countries - Deaths"
)

fig.show()

"""**OBJECTIVE 5 – CASE DISTRIBUTION ANALYSIS**

**13 – Pie Chart**
"""

fig = px.pie(
    names=["Confirmed","Deaths","Recovered","Active"],
    values=[total_confirmed,total_deaths,total_recovered,total_active],
    title="COVID Distribution"
)

fig.show()

"""**OBJECTIVE 6 – RELATIONSHIP ANALYSIS**

**14 – Confirmed vs Deaths**
"""

fig = px.scatter(
    df,
    x="Confirmed",
    y="Deaths",
    title="Confirmed vs Deaths"
)

fig.show()

"""**15 – Confirmed vs Recovered**"""

fig = px.scatter(
    df,
    x="Confirmed",
    y="Recovered",
    title="Confirmed vs Recovered"
)

fig.show()

"""**16 – Confirmed vs Active**"""

fig = px.scatter(
    df,
    x="Confirmed",
    y="Active",
    title="Confirmed vs Active"
)

fig.show()

"""**OBJECTIVE 7 – CORRELATION ANALYSIS**

**17 – Heatmap**
"""

fig = px.imshow(
    df.drop("Country", axis=1).corr(),
    text_auto=True,
    color_continuous_scale="Viridis",
    title="Correlation Matrix"
)

fig.show()

"""**OBJECTIVE 8 – INTERACTIVE VISUALIZATION**

**18 – Interactive Bar Chart**
"""

fig = px.bar(
    top10,
    x="Country",
    y="Confirmed",
    color="Confirmed",
    title="Top 10 Countries"
)

fig.show()

"""**19 – Interactive Scatter Plot**"""

fig = px.scatter(
    df,
    x="Confirmed",
    y="Deaths",
    size="Active",
    color="Recovered",
    hover_name="Country"
)

fig.show()

"""**OBJECTIVE 9 – DASHBOARD DEVELOPMENT**

**20 – Dashboard Layout**
"""

app = JupyterDash(__name__)

app.layout = html.Div([

    html.H1("COVID-19 Dashboard", style={"textAlign": "center"}),

    dcc.Dropdown(
        id="country",
        options=[{"label": i, "value": i} for i in df["Country"]],
        value=df["Country"].iloc[0]
    ),

    # Dynamic Country Graph
    dcc.Graph(id="graph"),

    # Bar Chart – Top affected countries
    dcc.Graph(
        figure=px.bar(
            top10,
            x="Country",
            y="Confirmed",
            title="Top 10 Countries"
        )
    ),

    # Line Chart – Cases trend
    dcc.Graph(
        figure=px.line(
            top10,
            x="Country",
            y="Confirmed",
            markers=True,
            title="Cases Trend (Line Chart)"
        )
    ),

    # Scatter Plot – Relationship
    dcc.Graph(
        figure=px.scatter(
            df,
            x="Confirmed",
            y="Deaths",
            size="Active",
            color="Recovered",
            hover_name="Country",
            title="Confirmed vs Deaths"
        )
    ),

    # Heatmap – Correlation
    dcc.Graph(
        figure=px.imshow(
            df.drop("Country", axis=1).corr(),
            text_auto=True,
            title="Correlation Matrix"
        )
    ),

    # Pie Chart – Case Distribution
    dcc.Graph(
        figure=px.pie(
            pie_data,
            values="Confirmed",
            names="Country",
            title="Case Distribution (Top 5 + Others)"
        )
    )

])

@app.callback(
    Output("graph", "figure"),
    Input("country", "value")
)
def update_graph(selected_country):

    data = df[df["Country"] == selected_country]

    fig = px.bar(
        x=["Confirmed","Deaths","Recovered","Active"],
        y=[
            data["Confirmed"].values[0],
            data["Deaths"].values[0],
            data["Recovered"].values[0],
            data["Active"].values[0]
        ],
        title=f"COVID Data - {selected_country}"
    )

    return fig

app.run()

"""**23 – Final Insights**"""

print("INSIGHTS:")

print("1. Countries with high confirmed cases have higher risk levels.")

print("2. There is a strong relationship between confirmed cases and deaths.")

print("3. Higher recovery numbers indicate improvement in healthcare systems.")

print("4. Active cases represent the current pandemic situation in each country.")

print("5. Data visualization helps understand trends and supports decision making.")