# -*- coding: utf-8 -*-
"""P7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrJoF4W0KoeU4d3YgJtLIOYbeJ1W4Jif

**PROJECT: COVID-19 DATA ANALYSIS & DASHBOARD SYSTEM**

**OBJECTIVE 1 – DATA COLLECTION**

**Install Dashboard Libraries**
"""

!pip install dash
!pip install jupyter-dash

"""**Import Required Libraries**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px

from jupyter_dash import JupyterDash
from dash import dcc, html
from dash.dependencies import Input, Output

"""**Mount Google Drive**"""

from google.colab import drive
drive.mount('/content/drive')

"""**Load Dataset from Google Drive**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/country_wise_latest.csv")

df.head()

"""**OBJECTIVE 2 – DATA CLEANING & PREPROCESSING**

**Select Required Columns**
"""

df = df[["Country/Region","Confirmed","Deaths","Recovered","Active"]]

df.columns = ["Country","Confirmed","Deaths","Recovered","Active"]

df.head()

"""**Check Missing Values**"""

print("Missing Values")
print(df.isnull().sum())

"""**Remove Duplicate Records**"""

df = df.drop_duplicates()

df.info()

"""**OBJECTIVE 3 – DESCRIPTIVE STATISTICS**

**Global Statistics**
"""

total_confirmed = df["Confirmed"].sum()
total_deaths = df["Deaths"].sum()
total_recovered = df["Recovered"].sum()
total_active = df["Active"].sum()

print("Total Confirmed Cases:", total_confirmed)
print("Total Deaths:", total_deaths)
print("Total Recovered:", total_recovered)
print("Total Active:", total_active)

"""**Statistical Summary**"""

df.describe()

"""**OBJECTIVE 4 – COUNTRY BASED ANALYSIS**

**Top 10 Countries by Confirmed Cases**
"""

top10 = df.sort_values(by="Confirmed",ascending=False).head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x="Confirmed",
    y="Country",
    data=top10,
    palette="Reds_r"
)

plt.title("Top 10 Countries with Highest Confirmed Cases")
plt.xlabel("Confirmed Cases")
plt.ylabel("Country")

plt.show()

"""**Top Countries by Deaths**"""

plt.figure(figsize=(10,6))

sns.barplot(
    x="Deaths",
    y="Country",
    data=top10,
    palette="coolwarm"
)

plt.title("Countries with Highest Death Counts")

plt.show()

"""**OBJECTIVE 5 – CASE DISTRIBUTION ANALYSIS**

**Pie Chart**
"""

cases = [total_confirmed,total_deaths,total_recovered,total_active]

labels = ["Confirmed","Deaths","Recovered","Active"]

plt.figure(figsize=(7,7))

plt.pie(
    cases,
    labels=labels,
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Global COVID-19 Case Distribution")

plt.show()

"""**OBJECTIVE 6 – RELATIONSHIP ANALYSIS**

**Confirmed vs Deaths**
"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="Confirmed",
    y="Deaths",
    data=df
)

plt.title("Relationship: Confirmed vs Deaths")

plt.show()

"""**Confirmed vs Recovered**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="Confirmed",
    y="Recovered",
    data=df
)

plt.title("Relationship: Confirmed vs Recovered")

plt.show()

"""**Active vs Confirmed**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="Confirmed",
    y="Active",
    data=df
)

plt.title("Relationship: Active vs Confirmed")

plt.show()

"""**OBJECTIVE 7 – CORRELATION ANALYSIS**

**Correlation Heatmap**
"""

plt.figure(figsize=(8,6))

corr = df.drop('Country', axis=1).corr()

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm"
)

plt.title("COVID Data Correlation Matrix")

plt.show()

"""**OBJECTIVE 8 – INTERACTIVE DATA VISUALIZATION**

**Interactive Bar Chart**
"""

fig = px.bar(
    top10,
    x="Country",
    y="Confirmed",
    color="Confirmed",
    title="Top 10 Countries by Confirmed Cases"
)

fig.show()

"""**Interactive Scatter Plot**"""

fig = px.scatter(
    df,
    x="Confirmed",
    y="Deaths",
    hover_name="Country",
    size="Active",
    color="Recovered",
    title="COVID Relationship Analysis"
)

fig.show()

"""**OBJECTIVE 9 – INTERACTIVE DASHBOARD**

**Dashboard Layout**
"""

app = JupyterDash(__name__)

app.layout = html.Div([

    html.H1("COVID-19 Data Analysis Dashboard",
            style={'textAlign':'center'}),

    dcc.Dropdown(
        id='country-dropdown',
        options=[{'label':i,'value':i} for i in df['Country']],
        value=df['Country'].iloc[0]
    ),

    dcc.Graph(id='covid-graph')

])

"""**Dashboard Callback**"""

@app.callback(
    Output('covid-graph','figure'),
    Input('country-dropdown','value')
)

def update_graph(selected_country):

    filtered = df[df["Country"] == selected_country]

    fig = px.bar(
        x=["Confirmed","Deaths","Recovered","Active"],
        y=[
           filtered["Confirmed"].values[0],
           filtered["Deaths"].values[0],
           filtered["Recovered"].values[0],
           filtered["Active"].values[0]
        ],
        labels={'x':'Case Type','y':'Count'},
        title=f"COVID Statistics for {selected_country}"
    )

    return fig

"""**Run Dashboard**"""

app.run()

"""**OBJECTIVE 10 – DASHBOARD INSIGHTS**

**Identify High-Risk Countries**
"""

high_risk = df.sort_values(by="Confirmed", ascending=False).head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x="Confirmed",
    y="Country",
    data=high_risk,
    palette="Reds"
)

plt.title("High Risk Countries Based on Confirmed Cases")
plt.xlabel("Confirmed Cases")
plt.ylabel("Country")

plt.show()

"""**Analyze Recovery Trends**"""

recovery = df.sort_values(by="Recovered", ascending=False).head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x="Recovered",
    y="Country",
    data=recovery,
    palette="Greens"
)

plt.title("Top Countries by Recovery Cases")
plt.xlabel("Recovered Cases")
plt.ylabel("Country")

plt.show()

"""**Observe Pandemic Patterns**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x="Confirmed",
    y="Active",
    data=df
)

plt.title("Pandemic Pattern: Confirmed vs Active Cases")
plt.xlabel("Confirmed Cases")
plt.ylabel("Active Cases")

plt.show()

"""**INSIGHTS & CONCLUSION**

**Project Insights**
"""

print("COVID-19 DATA ANALYSIS INSIGHTS")

print("1. Countries with higher confirmed cases are considered high-risk regions.")
print("2. Recovery trends indicate improvement in healthcare response.")
print("3. There is a strong relationship between confirmed cases and deaths.")
print("4. Active cases represent the current pandemic burden in each country.")
print("5. Data visualization helps understand COVID spread patterns.")
print("6. Interactive dashboards support better decision-making.")